DESIGN=testeISP
DESDIR=C:\Users\Lucas\OneDrive\Documentos\nascerr bootloader\Github\In_System_Programming_FPGA\testeISP\designer\testeISP
TARGET_DIR=C:\Users\Lucas\OneDrive\Documentos\nascerr bootloader\Github\In_System_Programming_FPGA\testeISP\designer\testeISP
FAM=SmartFusion2
DIE=PA4M2500
PACKAGE=vf256
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
